### ISSUE TITLE
Backpressure

### ISSUE THREAD

**Issue by timoxley** [kefirjs/kefir#115]
Would be great if kefir streams could exhibit backpressure. Any plans to implement?

**Comment by godDLL** [comment]
A way to deal with a backlog of unconsumed events in a stream? When the subscriber is lagging, or whatever?

Or specifically `Backpressure`?

**Comment by rpominov** [comment]
I'm also not sure what we can do in this direction. 

As I understand backpressure is a way for consumer to communicate with the source and control rate it's rate of events somehow. We currently don't have any such channel of communication from consumers to source, except consumer can unsubscribe, and if all consumers do that, the source will know.

Two things to note here:
 - In Kefir one source can have multiple consumers.
 - In most cases even if a source get a request from a consumer to slow down the rate, it won't be able to do anything about it as it can't control the rate itself (take `click` events as example).

**Comment by timoxley** [comment]
> When the subscriber is lagging

Correct. 

> backpressure is a way for consumer to communicate with the source and control it's rate of events somehow

Correct

> In Kefir one source can have multiple consumers.

This does complicate things.

**Comment by mAAdhaTTah** [comment]
I don't think we're going to be able to implement backpressure in Kefir, so I'm going to close this. I might suggest something like [Highland.js](https://highlandjs.org/) if you need that feature.
