### ISSUE TITLE
Mystified by concat behaviour, thought was a bug, now feature request

### ISSUE THREAD

**Issue by cefn** [kefirjs/kefir#123]
I had a test case where I was mystified why Kefir wasn't sending any events.

https://gist.github.com/cefn/324dc4157e431f37c982

It turns out to be a feature of the array traversal of concat which makes it very prone to silent failure if you invoke like...

```
Kefir.concat(obs1,obs2);
```

...instead of 

```
Kefir.concat([obs1,obs2]);
```

In any case this silent failure is a very tricky situation which would ideally be ironed out of the library It could be fixed by either...
- Failing harder when a non-array argument is passed (people using other stream libraries which support multiple ways of invoking would be very prone to this)
- Actively handle the case where a non-array argument is passed, and treat all the arguments as observables.

**Comment by godDLL** [comment]
This sounds much like the function composition magic in Bacon.

**Comment by mAAdhaTTah** [comment]
Closing in favor of #130.
