### ISSUE TITLE
Setup esm build for tree shaking benefits

### ISSUE THREAD

**Issue by zephraph** [kefirjs/kefir#250]
Being as this project is already using rollup, with a little extra configuration we could output an esm (es modules) build to so that consumers of the library using webpack or rollup could benefit from tree shaking any functionality they may not use. 

https://github.com/rollup/rollup/wiki/pkg.module

Even if there's not a whole lot of benefit from tree shaking, it's still a worthy cause. 

I may do a PR myself if you're open for that.

**Comment by rpominov** [comment]
Yes, good idea! In fact we already had it set up, but in a wrong way. We simply had a reference to uncompiled source. We need to create a special build where only `import/export` are left uncompiled, as the link say https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features
