### ISSUE TITLE
Bower not aware of kefirjs/kefir, still points to rpominov/kefir

### ISSUE THREAD

**Issue by wbercx** [kefirjs/kefir#263]
Hi,

It appears you have moved Kefir to `kefirjs/kefir`, but Bower is still pointing to `rpominov/kefir`, causing builds to fail as it has no releases.

I am aware Bower itself has been deprecated, but we have not gotten around to migrating to Yarn just yet. 

If it helps anyone else: we've worked around it by specifically pointing to a release in *this* repo in our `bower.json` file. 

```
"dependencies": {
    "kefir": "https://github.com/kefirjs/kefir.git#3.8.0"
}
```

This may catch some other people off-guard though.

**Comment by rpominov** [comment]
I've unregistered and registered it again pointing to the new repo. Should be fixed now.

**Comment by mAAdhaTTah** [comment]
@wbercx Does this resolve the issue for you?

**Comment by wbercx** [comment]
Works fine now. Thanks for that!
