### ISSUE TITLE
mapErrors vs flatMapErrors

### ISSUE THREAD

**Issue by ivan-kleshnin** [kefirjs/kefir#266]
`mapErrors` maps error to a new error
`flatMapErrors` maps error to a stream of values

I find this very counter-intuitive. Why it's made like that?

My expectation was to have both converting errors to values. I see little value in converting errors to another errors because errors are mostly `new Error` objects i.e. **instances** (prototype is important and immutable `x -> y`-like transformations aren't possible in general).

**Comment by rpominov** [comment]
The general idea of error related methods is to be symmetrical to similar value related methods. E.g. `mapErrors` is the same as `map` but for _errors_, `skipErrors` is the same as `skip` but for _errors_, etc. Hopefully, this makes API more intuitive, once you get that idea.

**Comment by ivan-kleshnin** [comment]
I think I get the idea but what does "for errors" mean. It may mean two things:

```
1) error -> error2
2) error -> value
```

`mapErrors` maps errors to errors (1)
`flatMapErrors` maps errors to values (2)

It's not symmetrical to value related methods where both `map` and `flatMap` map values to values.

**Comment by rpominov** [comment]
"error -> error2" this one.

> flatMapErrors maps errors to values

flatMap and flatMapErros can do both:

```js
// values -> values
s.flatMap(x => Kefir.constant(x))

// values -> errors
s.flatMap(x => Kefir.constantError(x))

// errors -> values
s.flatMapError(x => Kefir.constant(x))

// errors -> errors
s.flatMapError(x => Kefir.constantError(x))
```

**Comment by ivan-kleshnin** [comment]
Ouch. Now it makes sense to me. Closing...
