### ISSUE TITLE
fromEvents does not register listeners to browser extension APIs

### ISSUE THREAD

**Issue by solkaz** [kefirjs/kefir#267]
If I wanted to observe the `browser.webNavigation.onCompleted` event, I cannot use `fromEvents` to add the listener as expected:
```js
const stream = Kefir.fromEvents(browser.webNavigation, 'onCompleted', transformer);
```
because the function checks if the sub/unsub functions are members of the target (`browser.webNavigation`), when they are actually defined on `onCompleted`.

**Comment by AgentME** [comment]
Sorry that this hadn't gotten any attention previously!

`browser.webNavigation.onCompleted` handles event registration in a different way than Kefir.fromEvents is built to handle. The `browser.webNavigation` object doesn't have an interface matching a DOM EventTarget, a Node.JS EventEmitter object, or jQuery-style on/off methods, so it's not expected that Kefir.fromEvents should work with it.

DOM EventTargets, Node.JS EventEmitter objects, and jQuery-style objects have event listener registration/removal methods which take an event name and callback as parameters. `browser.webNavigation.onCompleted` has a method taking a callback and an additional webNavigation-specific filter parameter, so I don't expect Kefir.fromEvents to be adapted to it. Its specific API seems to only be found in Chrome/Firefox browser extension APIs, so at this time I don't expect Kefir to adopt a new built-in function for adapting with it.

Within your project, you could define an adapter function like this:

```js
function fromBrowserEvents(object, event, ...extra) {
  return Kefir.stream(em => {
    object[event].addListener(em.value, ...extra);
    return () => {
      object[event].removeListener(em.value);
    };
  });
}
```
