### ISSUE TITLE
Current state policies

### ISSUE THREAD

**Issue by ivan-kleshnin** [kefirjs/kefir#278]
**Current state** behavior is kinda weird. Some operators see it as a normal event and some don't without any special mention in docs. For example:

```js
K.constant("foo")
  .skipWhile(x => true) // treats current state as a normal event
  .observe() // -|

K.constant("foo")
  .map(x => true) // treats current state as a normal event
  .observe() // -true|
```

```js
K.constant("foo")
  .delay(1000) // no effect, current state slips through
  .observe() // -"foo"|

K.constant("foo")
  .throttle(1000) // no effect, current state slips through
  .observe() // -"foo"|
```

It seems time-related operators behave differently from value-related operators in this aspect, 
but I can't say for sure without digging into sources.

I dunno which behavior is better, I think I'd like "current state" to be a normal event, affected by `delay` and others. Otherwise it behaves kinda like "error" event which violates my expectations.

**Comment by mAAdhaTTah** [comment]
> It seems time-related operators behave differently from value-related operators in this aspect

Without digging in as well, this seems reasonable. The event is "current", so it makes sense to me that it should be emitted immediately, without being impacted by `delay` and the like. When you subscribe to a Property that has a current event, you want to know what that value is _right now_. Letting `delay` impact whether you get the current value changes that expectation.
