### ISSUE TITLE
Shouldn't a property only emit on "new values"? Proposing `onChange()`

### ISSUE THREAD

**Issue by DanweDE** [kefirjs/kefir#287]
I get that

```
var stream = Kefir.sequentially(50, [1, 2, 2, 3]);
stream.log('stream')

// stream: --1--2--2--3--
```

But why would a property behave the same?

```
var property = Kefir.sequentially(50, [1, 2, 2, 3]).toProperty()
property.log('property')

// property: --1--2--2--3X
```

while I would really expect

```
// property: --1--2-----3X
```

basically I don't get why `property.onValue(cb)` would invoke `cb` when the property's value did not actually "change". **Maybe there could be a `property.onChange(cb)` behaving as described above.**

Is there currently a way to get a property behaving this way given `property` in the example above? Thank you for any insights on this.

**Comment by Macil** [comment]
There's a skipDuplicates() method on all Kefir observables, so `property.skipDuplicates().onValue(cb)` would do what you describe.
