### ISSUE TITLE
A big "Thank You" to Kefir developers

### ISSUE THREAD

**Issue by episage** [kefirjs/kefir#299]
I'd like to thank you for this library. It fulfils its promise of being high performance.
Also, it is user friendly (fluent API) and the documentation is clear to me.

RxJS brought me far but I reached a point where I need to scale up. Memory and CPU cycles became precious.
RxJS due to its poor performance for big data sets made me look for something more efficient.
I picked up a `high-performance` language `Nim` and tried to rewrite my data processing algo.
It turned out that I Nim is so slow while reading from a file that my as-in-the-nodejs-docs JS implementation outperforms it by a factor of 5x or more (reading line by line from ~200MB file). Funny..

I even tried to write my own streams library based on callbacks. It performed well but writing everything from scratch was a big time consumer.

And then I found Kefir and I fell in love with it...

I never thought NodeJS can be that fast and that performant

**Comment by mAAdhaTTah** [comment]
Thank you so much for the kind words!
