### ISSUE TITLE
How to import Kefir within Rollup library

### ISSUE THREAD

**Issue by antonioaguilar** [kefirjs/kefir#300]
Hi all, I'm writing a library using Rollup and I would like to use some Kefir methods and take advantage of tree-shaking.  This has been discussed in #250 but as of today, what is the correct way to import Kefir within a rollup project?

Importing kefir using: 
```javascript
import kefir from 'kefir'; 
```
Doesn't seem to work ... below is my rollup configuration:

```javascript
// rollup.config.js
import babel from 'rollup-plugin-babel';

export default {

  input: './src/main.js',

  output: {
    file: 'dist/library.min.js',
    format: 'umd',
    name: 'Library',
    sourcemap: true,
    globals: {
      'kefir': 'kefir'
    }
  },

  plugins: [
    babel({
      exclude: 'node_modules/**'
    })
  ]

}
```

Any ideas on how to correctly import Kefir as ES6 module?

**Comment by mAAdhaTTah** [comment]
Two questions:

1. What error(s) are you getting?
2. Why is `kefir` listed as a global?

**Comment by mAAdhaTTah** [comment]
You've configured Rollup to expect Kefir to be available as a global variable, so you need to make it available as such in order for this to work.

That said, this is a Rollup issues, and I'm not really a Rollup expert. I might suggest taking this question to StackOverflow or the Rollup issue tracker if you still have problems with this.
