### ISSUE TITLE
Synchronous emit in flush method of debounce produces incorrect result

### ISSUE THREAD

**Issue by betalb** [kefirjs/kefir#307]
If you will try to do synchronous emit in debounced observable incorrect sequence of events will be produced

i.e.
```javascript
const a = Kefir.pool();
const b = a.debounce(100).spy();
a.plug(b.filter((val) => val === 1).map(() => 2));
a.plug(Kefir.constant(1));
a.observe();
```

Expected output
```
100ms [pool.debounce] <value> 1
200ms [pool.debounce] <value> 2
```

Actual output
```
100ms [pool.debounce] <value> 1
200ms [pool.debounce] <value> null
```

**Comment by mAAdhaTTah** [comment]
Without having investigated, the issue is probably less about synchronous emit and more about the circular dependency between `a` & `b`.

**Comment by betalb** [comment]
yes, there is a cycle, but it is not infinite and is actually done to illustrate an issue

Here is another more dirty example that produces the same result
```
let e;
Kefir.stream((emitter) => { e = emitter; })
  .debounce(100)
  .withHandler((emitter, event) => {
    if (event.type === 'value' && event.value === 1) {
      e.emit(2);
    }
    emitter.emitEvent(event)
  }).log();
e.emit(1);
```

Actually I created PR that should highlight where the issues seems to be. And there are similar problems in `buffer-by`, `buffer-while-by` (I just wanted to create cleaner test case before creating separate ticket)

**Comment by rpominov** [comment]
This is documented behaviour:

![image](https://user-images.githubusercontent.com/825702/92496181-7e3bee00-f200-11ea-9b00-211d9992ee05.png)

Although documentation might be more clear probably. My idea was back then is that synchronous events is not a use case I wanted to support in the library in general.

**Comment by betalb** [comment]
@rpominov I'm not following documentation quote, for me it sound like a different case, which I never faced 🙂

This issue is not with the fact that some value is emitted without being debounced, but completely wrong value (`null`) being emitted

Also I've provided 2nd example that doesn't use properties and here is 1st example without using properties either

```javascript
const a = Kefir.pool();
const b = a.debounce(100).spy();
a.plug(b.filter((val) => val === 1).map(() => 2));
a.plug(Kefir.stream(emitter => { emitter.emit(1) }));
a.observe();
```

**Comment by mAAdhaTTah** [comment]
@rpominov The issue isn't that it's emitted synchronously (it actually isn't, according to the issue description), but that the second event is dropped.

**Comment by rpominov** [comment]
Ah, right, sorry

**Comment by bpinto** [comment]
Hey guys, @betalb opened a PR fixing this, do you think we could merge his PR?

**Comment by mAAdhaTTah** [comment]
@bpinto Done. Let me get a release out this weekend.
