### ISSUE TITLE
Add fromArray method

### ISSUE THREAD

**Issue by brandonhorst** [kefirjs/kefir#5]
Bacon and Rx define a fromArray method that works exactly like `Kefir.once`, but emits multiple items passed in as an array.

```
Kefir.fromArray([1, 2, 3]).log();
<value> 1
<value> 2
<value> 3
<end>
```

Would be nice to have.

**Comment by gnapse** [comment]
I came to this repo to find some issue about `fromArray` not being available, or to post that issue myself. But I have to say that after reading this discussion and the referenced issue in the bacon library, and after doing some tests around all that, I'm glad this function is not included (or any other synchronous sources for that matter). It forces other developers to dig into the issue and find about the drawbacks of synchronous streams, just like I did. As for a workaround, you can always call `sequentially` with a very low interval value, perhaps even zero.
